### ISSUE TITLE
Ability to combine data for a location from multiple sources

### ISSUE THREAD

**Issue by lazd** [covidatlas/li#198]
## Description.

See https://github.com/covidatlas/coronadatascraper/issues/410

## Describe the solution you'd like**

Consider the ability to take certain fields from one source and combine it with fields from another source.

**Comment by jzohrab** [comment]
This is implemented in the current reports.  See docs https://github.com/covidatlas/li/blob/master/docs/reports.md#combining-data-sources.

For example, in timeseries-byLocation.js, a location may have:

```
  "timeseriesSources": {
    "2020-05-21..2020-06-18": "us-ca",
    "2020-06-19": { "us-ca": [ "deaths" ], "jhu": [ "cases" ] }
  },
```

This means that from 2020-05-21 to 2020-06-18, all fields of data for all dates are from the us-ca source.
For 2020-06-19, us-ca supplied deaths, and jhu supplied cases.

This felt like the clearest way to present the data source, and allowed for some "compression" of the data, rather than labelling the source for each and every data point.

`src/events/reports/generate-data/_multivalent-record.js` handles combining everything.
