### ISSUE TITLE
Marin County cases data is hugely wrong.

### ISSUE THREAD

**Issue by kengoy** [covidatlas/li#358]
"Marin County" cases data turns hugely wrong from July 24.

      "2020-07-22": {
        "cases": 2398,
        "deaths": 35,
        "tested": 45815,
        "hospitalized": 99,
        "recovered": 1851,
        "icu": 0,
        "growthFactor": 1.03
      },
      "2020-07-23": {
        "cases": 2416,
        "deaths": 35,
        "tested": 46430,
        "hospitalized": 99,
        "recovered": 1916,
        "icu": 0,
        "growthFactor": 1.01
      },
      "2020-07-24": {
        **"cases": 4489,**
        "deaths": 39,
        "tested": 46906,
        "hospitalized": 99,
        "recovered": 2000,
        "icu": 0,
        "growthFactor": 1.86
      },
      "2020-07-25": {
        **"cases": 4489,**
        "deaths": 39,
        "tested": 46906,
        "hospitalized": 99,
        "recovered": 2000,
        "icu": 0,
        "growthFactor": 1
      },

FYI: COVID-19 in Marin County:  https://coronavirus.marinhhs.org/

**Comment by jzohrab** [comment]
Hello @kengoy , thanks for the issue.

I believe our number is valid.  We're showing cumulative cases over time.  The page you reference is giving current state.  In other words, there are 2706 current cases, but there used to be 2292 more (which have since recovered).  2706 + 2292 = 4998 (as of today).

I've asked our team to verify the interpretation of the data to be sure.  Keeping this open for now.

----

Some notes:

In the `timeseries-byLocation.json` report, I checked the dateSources for Marin County:

```
    "dateSources": {
      "2020-01-24..2020-02-25": "jhu-usa",
...
      "2020-03-20": "jhu-usa",
      "2020-03-21..2020-07-31": "us-ca-mercury-news"
    },
```

so we've been using us-ca-mercury-news source as the data source for several months.  That code is in `src/shared/sources/us/ca/mercury-news.ca`, and you'll see it's pulling from `https://docs.google.com/spreadsheets/d/1CwZA4RPNf_hUrwzNLyGGNHRlh1cwl8vDHwIoae51Hac/gviz/tq?tqx=out:csv&sheet=timeseries`.

That [google spreadsheet](https://docs.google.com/spreadsheets/d/1CwZA4RPNf_hUrwzNLyGGNHRlh1cwl8vDHwIoae51Hac/edit#gid=673514375&fvid=5665043) is apparently sourcing its data from https://coronavirus.marinhhs.org/surveillance#today.

As of now that site says

![image](https://user-images.githubusercontent.com/1637133/88968838-f3b9b380-d27d-11ea-84eb-89ca8f473820.png)

They're reporting "cases" = "cases + recovered", which makes sense.

**Comment by kengo-sony** [comment]
Hello @jzohrab , thank you for checking this and gave me the explanation in detail.
I was wondering and doubt the number because  
 - 2020-07-23 shows "cases": **2416**,  "recovered": 1916 which "cases" number does not include the recovered number
but
 - 2020-07-24 shows "cases": **4489**, "recovered": 2000 which "cases" number started to include the recovered number

Our site(https://panda.baybrigades.org/) shows a time series chart for San Francisco Bay Area Counties referring the dataset 
 scraped by Corona Data Scraper  (Thanks so so much!!), and Marin County shoes a huge jump on 7/24.

![Screen Shot 2020-07-31 at 1 32 44 AM](https://user-images.githubusercontent.com/57465051/89016862-491db100-d2ce-11ea-8e05-a216d32f5b6c.png)

I am still not quite sure if Marin County Public Health site is showing the data as "cases" = "cases + recovered".  I will check.

**Comment by kengo-sony** [comment]
I think I found the reason. According to https://coronavirus.marinhhs.org/surveillance, Marin County Public Health's site number 2,706 does not include the number of San Quentin inmates which counts 2,168.  But other sites including NYT, mercury news, SF Chronicle etc show the number as 4,874 including the inmates.  I guess most of the sites started to count the number including the inmates from 7/24.  Still, Marin County Public Health's site continues to show the number excluding the inmates. That's why we see the huge difference.  Now it makes sense to me.

![Screen Shot 2020-07-29 at 8 57 07 PM](https://user-images.githubusercontent.com/57465051/89017815-c1d13d00-d2cf-11ea-80c1-becaf09e21c0.png)

**Comment by kengo-sony** [comment]
Sorry, I noticed I was using my different github account. I am @kengoy as well.

**Comment by jzohrab** [comment]
Cheers @kengo-sony / @kengoy . ありがとうございます。これで、良いですか？Do you think we can close this issue?

**Comment by kengo-sony** [comment]
@jzohrab Yes, we can close this issue. Thank you. Arigato.

**Comment by 1ec5** [comment]
#379 adds a scraper for Marin County that relies on Marin Health & Human Services as its source. I think it would be beneficial to use the county’s dataset, even if it differs from aggregators, in part because allows the time series to be internally consistent.
